from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(820, 444)
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(120, 160, 181, 20))
        self.checkBox.setObjectName("checkBox")
        self.wykres = QtWidgets.QLabel(Dialog)
        self.wykres.setGeometry(QtCore.QRect(450, 20, 341, 401))
        self.wykres.setStyleSheet("background-color: rgb(228, 255, 219);")
        self.wykres.setText("")
        self.wykres.setObjectName("wykres")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(40, 140, 331, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 20, 351, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.linePokolenia = QtWidgets.QLineEdit(self.layoutWidget)
        self.linePokolenia.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.linePokolenia.setObjectName("linePokolenia")
        self.gridLayout.addWidget(self.linePokolenia, 0, 1, 1, 1)
        self.lineRegula = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineRegula.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineRegula.setMaxLength(3)
        self.lineRegula.setObjectName("lineRegula")
        self.gridLayout.addWidget(self.lineRegula, 1, 1, 1, 1)
        self.labelRegula = QtWidgets.QLabel(self.layoutWidget)
        self.labelRegula.setObjectName("labelRegula")
        self.gridLayout.addWidget(self.labelRegula, 1, 0, 1, 1)
        self.labelPokolenia = QtWidgets.QLabel(self.layoutWidget)
        self.labelPokolenia.setObjectName("labelPokolenia")
        self.gridLayout.addWidget(self.labelPokolenia, 0, 0, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(120, 230, 179, 181))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.buttonWykonaj = QtWidgets.QPushButton(self.layoutWidget1)
        self.buttonWykonaj.setObjectName("buttonWykonaj")
        self.verticalLayout.addWidget(self.buttonWykonaj)
        self.buttonZapisz = QtWidgets.QPushButton(self.layoutWidget1)
        self.buttonZapisz.setObjectName("buttonZapisz")
        self.verticalLayout.addWidget(self.buttonZapisz)
        self.buttonReset = QtWidgets.QPushButton(self.layoutWidget1)
        self.buttonReset.setObjectName("buttonReset")
        self.verticalLayout.addWidget(self.buttonReset)
        self.pushButtonWyswietlPoza = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonWyswietlPoza.setObjectName("pushButtonWyswietlPoza")
        self.verticalLayout.addWidget(self.pushButtonWyswietlPoza)
        self.layoutWidget2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 190, 430, 24))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelLosowo = QtWidgets.QLabel(self.layoutWidget2)
        self.labelLosowo.setObjectName("labelLosowo")
        self.horizontalLayout.addWidget(self.labelLosowo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.linePstwo = QtWidgets.QLineEdit(self.layoutWidget2)
        self.linePstwo.setEnabled(False)
        self.linePstwo.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.linePstwo.setObjectName("linePstwo")
        self.horizontalLayout.addWidget(self.linePstwo)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Automat komórkowy"))
        self.checkBox.setText(_translate("Dialog", "Chcę wykonać automat losowy"))
        self.labelRegula.setText(_translate("Dialog", "Reguła:"))
        self.labelPokolenia.setText(_translate("Dialog", "Liczba pokoleń:"))
        self.buttonWykonaj.setText(_translate("Dialog", "Wykonaj"))
        self.buttonZapisz.setText(_translate("Dialog", "Zapisz"))
        self.buttonReset.setText(_translate("Dialog", "Reset"))
        self.pushButtonWyswietlPoza.setText(_translate("Dialog", "Wyświetl wykres poza oknem"))
        self.labelLosowo.setText(_translate("Dialog", "Prawdopodobieństwo wystąpienia żywej komórki:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
